'use client';
import { Context } from '@/hooks';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Trip Management',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [selectedKey, setSelectedKey] = useState('1');
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Context.Provider value={{ selectedKey, setSelectedKey }}>
          {children}
        </Context.Provider>
      </body>
    </html>
  );
}
